remove(Team)
remove(Style)
remove(row.toadd)
remove(right.index.2)
remove(receiver)
remove(receive.location)
remove(possession)
remove(Position)
remove(Positions)
remove(Player)
remove(passer)
remove(body.part)
remove(columns.to.keep)
remove(Do)
remove(event.files)
remove(i)
remove(jordi.index)
remove(Lokation)
remove(match.files)
remove(p)
remove(palette)
remove(pass.angle)
remove(Name)
remove(pass.index)
remove(pass.length)
remove(pass.location)
remove(pass.type)
remove(Spieler)
remove(rightraw)
remove(right.temp)
remove(right.list)
remove(pass.temp)
remove(matches.list)
remove(match.temp)
remove(matches)
remove(jordi.temp)
remove(jordi.list)
remove(jordi_raw)
remove(event.temp)
remove(event.list)
remove(competitions)
---------
remove(passmatches.df)
remove(matches.list)
remove(matches)
remove(match.temp)

remove(all)
remove(all.matches.clean)
remove(all.matches.df)

remove(jordi_raw)
remove(event.list)
remove(event.temp)


----
  